Python is a **high-level language** because we don't have to manually allocate memory or specifyhow the CPU performs certain operations. A low-level language like C gives us this control andlets us improve specific code performance, but it involves a tradeoff in programmer productivity.The NumPy library lets us write code in Python but take advantage of the performance that Coffers. 
The NumPy library takes advantage of a processor feature called **Single Instruction Multiple Data (SIMD)** to process data faster. SIMD allows a processor to perform the same operation on multiple data points in a single processor cycle:

In [5]:
import numpy as np

# covert a list to nd.array
data_list = [1,2,3,4]
data_ndarray = np.array(data_list)
print(data_ndarray)


[1 2 3 4]
Size of nparray (4,)


In [2]:
# covert a list to nd.array
nparray_to_list = list(data_ndarray)
nparray_to_list

[1, 2, 3, 4]

In [36]:
# check size of nparray
data_ndarray = np.array([[5, 10, 15], 
                         [20, 25, 30]])
print('Size of nparray', data_ndarray.shape)
data_ndarray

Size of nparray (2, 3)


array([[ 5, 10, 15],
       [20, 25, 30]])

In [8]:
# ndarray[row_index,column_index]
# access data from a cell 
data_ndarray[1,1]


25

In [11]:
# Let's continue by learning how to select one or more columns of data:
data_ndarray = np.array([[5, 10, 1], 
                         [20, 25, 2],
                         [33,34,3]])

sel_np = data_ndarray[:,2]
sel_np

array([1, 2, 3])

In [16]:
# select two columns
data_ndarray = np.array([[5, 10, 1,2,100], 
                         [20, 25, 2,3,101],
                         [33,34,3,4,102]])

two_columns = data_ndarray[:, 2:4]
two_columns

array([[1, 2],
       [2, 3],
       [3, 4]])

In [15]:
#Selecting multiple specific column
data_ndarray = np.array([[0, 10, 1,2,100], 
                         [0, 25, 2,3,101],
                         [0,34,3,4,102]])

cols = [0,2,3]
three_columns = data_ndarray[:, cols]

three_columns


array([[0, 1, 2],
       [0, 2, 3],
       [0, 3, 4]])

In [19]:
#If we want to select a partial 1D slice of a row or column, we can combine 
# a single value for one dimension with a slice for the other dimension
print('''
XXXXX
XX..X
XXXXX
''')

data_ndarray = np.array([[0, 10, 1,2,100], 
                         [0, 25, 2,3,101],
                         [0,34,3,4,102]])

sel_data = data_ndarray[1, 2:4]
sel_data


XXXXX
XX..X
XXXXX



array([2, 3])

In [22]:
# Lastly, if we want to select a 2D slice, we can use slices for both dimensions:

print('''
XXXXX
...XX
...XX
XXXXX
''')

data_ndarray = np.array([[0,10,1,2,100,200], 
                         [0,25,2,3,101,201],
                         [0,34,3,4,102,203],
                         [0,37,4,5,103,204]])

sel_data = data_ndarray[1:3, :3]
sel_data


XXXXX
...XX
...XX
XXXXX



array([[ 0, 25,  2],
       [ 0, 34,  3]])

NumPy ndarrays allow us to select data much more easily. Beyond this, the selection is much faster when working with **vectorized operations** because the operations apply to multiple data points at once.

In [23]:
# # convert the list of lists to an ndarray
# my_numbers = np.array(my_numbers)

# # select each of the columns - the result
# # of each will be a 1D ndarray
# col1 = my_numbers[:,0]
# col2 = my_numbers[:,1]

# # add the two columns
# sums = col1 + col2

# We could simplify this further if we wanted to:
# sums = my_numbers[:,0] + my_numbers[:,1]

The result of adding two 1D ndarrays is a 1D ndarray of the same shape (or dimensions) as the original. In this context, we can also call ndarrays **vectors**, a term from linear algebra. We call adding two vectors together **vector addition.**

In [30]:
a = np.array([ [ 22, 25,  2],
               [ 22, 34,  3],
               [ 22, 66,  8],
               [ 22, 1,  6]])

b = a[:,0] + a[:,1]
b

array([47, 56, 88, 23])

- vector_a + vector_b — addition
- vector_a - vector_b — subtraction
- vector_a * vector_b — multiplication (this is unrelated to the vector multiplication used in linear algebra).
- vector_a / vector_b - division

In [31]:
minimum = b.min()
maximum = b.max()
mean = b.mean()
summ = b.sum()
print('minimum',minimum)
print('maximum',maximum)
print('mean',mean)
print('sum',summ)

minimum 23
maximum 88
mean 53.5
sum 214


### [NumPy ndarray documentation](https://app.dataquest.io/c/54/m/289/introduction-to-numpy/10/calculating-statistics-for-1-d-ndarrays) - check for more information 

- len()  -- is a **function** 
- list.append()   -- **method** - methods are special functions that belong to a specific type of object.

In NumPy, sometimes operations implement as both methods and functions, which can be confusing.
To remember the right terminology, anything that starts with np (e.g., np.mean()) is a function, and anything expressed with an object 'or variable' name first e.g., var_name.mean() is a method. 


In [47]:
import random 

l = []

rows, columns = 5, 3

for i in range(rows):
    s = []
    
    for j in range(columns):
        e = random.randint(0,90)
        s.append(e)
    l.append(s)
    print(s)

print()

nparr = np.array(l)

print(nparr)
print('''
Some statistics with np:
Max of the whole table: {}
Max of each row: {}
Max of each column: {}
'''.format(
nparr.max(),
nparr.max(axis=1),
nparr.max(axis=0)
    
))


[13, 88, 18]
[36, 55, 56]
[74, 12, 33]
[62, 57, 13]
[51, 11, 17]

[[13 88 18]
 [36 55 56]
 [74 12 33]
 [62 57 13]
 [51 11 17]]

Some statistics with np:
Max of the whole table: 88
Max of each row: [88 56 74 62 51]
Max of each column: [74 88 56]



Creating a random 2D Np Array in one **line code :)**

In [48]:
import random 

rows, columns = 5, 3
li = np.array([[random.randint(0,9) for j in range(columns)] for i in range(rows)])

nparrli

array([[1, 4, 4],
       [9, 1, 4],
       [8, 1, 6],
       [0, 2, 0],
       [0, 3, 4]])